// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * cxadc-win - CX2388x ADC DMA driver for Windows
 *
 * Copyright (C) 2024 Jitterbug
 *
 * Based on the Linux version created by
 * Copyright (C) 2005-2007 Hew How Chee <how_chee@yahoo.com>
 * Copyright (C) 2013-2015 Chad Page <Chad.Page@gmail.com>
 * Copyright (C) 2019-2023 Adam Sampson <ats@offog.org>
 * Copyright (C) 2020-2022 Tony Anderson <tandersn@cs.washington.edu>
 */

#pragma once

DEFINE_GUID(GUID_DEVINTERFACE_CXADCWIN,
    0x13EF40B0, 0x05FF, 0x4173, 0xB6, 0x13, 0x31, 0x41, 0xAD, 0x2E, 0x37, 0x62);

#define CX_IOCTL_SET_CRYSTAL \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x900, METHOD_BUFFERED, FILE_WRITE_DATA)

#define CX_IOCTL_GET_CRYSTAL \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x960, METHOD_BUFFERED, FILE_READ_DATA)

#define CX_IOCTL_SET_VMUX \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x901, METHOD_BUFFERED, FILE_WRITE_DATA)

#define CX_IOCTL_GET_VMUX \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x961, METHOD_BUFFERED, FILE_READ_DATA)

#define CX_IOCTL_SET_LEVEL \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x902, METHOD_BUFFERED, FILE_WRITE_DATA)

#define CX_IOCTL_GET_LEVEL \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x962, METHOD_BUFFERED, FILE_READ_DATA)

#define CX_IOCTL_SET_TENBIT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x903, METHOD_BUFFERED, FILE_WRITE_DATA)

#define CX_IOCTL_GET_TENBIT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x963, METHOD_BUFFERED, FILE_READ_DATA)

#define CX_IOCTL_SET_SIXDB \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x904, METHOD_BUFFERED, FILE_WRITE_DATA)

#define CX_IOCTL_GET_SIXDB \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x964, METHOD_BUFFERED, FILE_READ_DATA)

#define CX_IOCTL_SET_CENTER_OFFSET \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x905, METHOD_BUFFERED, FILE_WRITE_DATA)

#define CX_IOCTL_GET_CENTER_OFFSET \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x965, METHOD_BUFFERED, FILE_READ_DATA)
