name: "Build"

on:
   workflow_dispatch:
   
jobs:
  build-driver:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]
    runs-on: windows-2022
    env:
      solution_path: cxadc-win.sln
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
  
      - name: Build driver
        run: |
          msbuild ${{ env.solution_path }} -target:cxadc-win -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }}

      - name: Build tool
        run: |
          dotnet publish cxadc-win-tool -r win-${{ matrix.platform }}

      - name: Create release directory
        run: |
          New-Item -ItemType Directory -Path .\release
          Copy-Item -Path .\x64\Release\cxadc-win\cxadc-win.cat -Destination .\release\
          Copy-Item -Path .\x64\Release\cxadc-win\cxadc-win.sys -Destination .\release\
          Copy-Item -Path .\x64\Release\cxadc-win\cxadc-win.inf -Destination .\release\
          Copy-Item -Path .\x64\Release\cxadc-win.pdb -Destination .\release\
          Copy-Item -Path .\cxadc-win-tool\bin\Release\net8.0-windows\win-x64\publish\cxadc-win-tool.exe -Destination .\release\
          Copy-Item -Path .\cxadc-win-tool\bin\Release\net8.0-windows\win-x64\publish\cxadc-win-tool.pdb -Destination .\release\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cxadc-win
          path: release
          if-no-files-found: error
